### PR TITLE
Reminder beta

### PR DESCRIPTION
**Pull request by gaetan-cordonnier**

### CODE REVIEW

**Review by ThomasDruart — DISMISSED** [review]
Ok, good job (expect for the indentation ;) )

**Review by ThomasDruart — DISMISSED** [review]
Good job ! 👍

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by ThomasDruart — APPROVED** [review]
Ok, no more conflicts

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
